config/routes.rb
Rails.application.routes.draw do

  get 'consults', to: 'consult#index'

  get 'consults/:id', to: 'consult#show', as: 'consult_show'

  get 'consult/complain'

  get 'consult/feedback'

  get 'consult/flow'

  get 'consult/justice'

  get 'consult/register'

  get 'consult/law'

  post 'consult/create'

  get 'home/index'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post '/consults/:consult_id/comments', to: 'comments#create', as: 'consult_comments'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :consult
  belongs_to :user
  mount_uploader :attachment, AttachmentUploader
end

app/models/consult.rb
class Consult < ApplicationRecord
  has_many :comments
  belongs_to :user

  enum question_type: [ :法律咨询, :立案咨询, :司法确认, :案件流程查询, :举报投诉, :信访申诉 ]
  mount_uploader :attachment, AttachmentUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :comments
  has_many :consults
  enum user_type: [:村网络员, :法庭网络员]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @consult = Consult.find(params[:consult_id])
    @comment = @consult.comments.create(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to consult_show_path(@consult)
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :attachment)
  end
end

app/controllers/consult_controller.rb
class ConsultController < ApplicationController
  before_action :authenticate_user!

  def index
    @consults = Consult.all
  end

  def show
    @consult = Consult.find(params[:id]);
  end

  def law
    @consult = Consult.new
    @consult.question_type = '法律咨询'
  end

  def register
    @consult = Consult.new
    @consult.question_type = '立案咨询'
  end

  def justice
    @consult = Consult.new
    @consult.question_type = '司法确认'
  end

  def flow
    @consult = Consult.new
    @consult.question_type = '案件流程查询'
  end

  def feedback
    @consult = Consult.new
    @consult.question_type = '举报投诉'
  end

  def complain
    @consult = Consult.new
    @consult.question_type = '信访申诉'
  end

  def create
    @consult = Consult.new(consult_params)
    @consult.user = current_user
    @consult.save
    redirect_to consult_show_path(@consult)
  end

  private
  def consult_params
    params.require(:consult).permit(:question_type, :title, :time, :address, :contact, :phone, :question, :attachment, :member)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private
  def sign_up_params
    params.require(:user).permit(:user_type, :email, :password, :password_confirmation)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/consult_helper.rb
module ConsultHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="control-group">
    <div class="control-label-area">答复意见:</div>
    <div class="answer-body"><%= comment.body %></div>
  </div>
  <div class="control-group">
    <div class="control-label-area">附件<%= link_to '下载', comment.attachment.url %></div>
  </div>
</div>

app/views/consult/_form.html.erb
<%= render 'header' %>
<div class="container home">
  <div class="left">
    <%= image_tag('left_logo.png', class: 'logo')%>
  </div>
  <div class="right consult">
    <%= form_for @consult ,html: { multipart: true, class: 'form-signin consult-form' }, url: consult_create_url do |f| %>
        <h2 class="form-signin-heading consult-title"><%= @consult.question_type %></h2>
        <div class="type">
          <%= f.text_field :question_type %>
        </div>
        <div class="control-group">
          <div class="control-label">时间:</div>
          <%= f.text_field :time, class: 'control-item', 'data-provide': 'datepicker' %>
        </div>
        <div class="control-group">
          <div class="control-label">名称:</div>
          <%= f.text_field :title, class: 'control-item' %>
        </div>

        <div class="control-group">
          <div class="control-label">地址:</div>
          <%= f.text_field :address, class: 'control-item' %>
        </div>

        <div class="control-group">
          <div class="control-label">联系人:</div>
          <%= f.text_field :contact, class: 'control-item' %>
        </div>

        <div class="control-group">
          <div class="control-label">联系电话:</div>
          <%= f.text_field :phone, class: 'control-item' %>
        </div>

        <div class="form-group control-group">
          <div class="control-label-area">咨询问题:</div>
          <%= f.text_area :question, class: 'control-area' %>
        </div>

        <div class="form-group control-group">
          <div class="control-label-area">附件</div>
          <%= f.file_field :attachment, class: 'btn btn-default' %>
        </div>

        <div class="form-group">
          <%= f.submit '提交' ,class: 'btn btn-lg btn-default btn-block'%>
        </div>
    <% end %>
  </div>
</div>

app/views/consult/_header.html.erb
<nav class="navbar navbar-default custom-nav">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "主页", root_path, class: 'navbar-brand nav-item' %>
      <%= link_to "咨询列表", consults_path, class: 'navbar-brand nav-item' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-item' %></li>
        <% else %>
            <li><%= link_to 'Login', new_user_session_path, class: 'nav-item' %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/consult/complain.html.erb
<%= render 'form' %>

app/views/consult/feedback.html.erb
<%= render 'form' %>

app/views/consult/flow.html.erb
<%= render 'form' %>

app/views/consult/index.html.erb
<%= render 'header' %>
<table class="table custom-tab">
  <thead>
  <tr>
    <th>#</th>
    <th>时间</th>
    <th>名称</th>
    <th>地址</th>
    <th>联系人</th>
    <th>联系电话</th>
    <th>咨询问题</th>
    <th>附件</th>
    <th>问题类型</th>
  </tr>
  </thead>
  <tbody>
  <% @consults.each do |consult| %>
      <tr>
        <th scope="row"><%= link_to '查看', consult_show_path(consult) %></th>
        <td><%= consult.time %></td>
        <td><%= consult.title %></td>
        <td><%= consult.address %></td>
        <td><%= consult.contact %></td>
        <td><%= consult.phone %></td>
        <td><%= consult.question %></td>
        <td>
          <% if consult.attachment %>
            <%= link_to '下载', consult.attachment.url %>
          <% end %>
        </td>
        <td><%= consult.question_type %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/consult/justice.html.erb
<%= render 'form' %>

app/views/consult/law.html.erb
<%= render 'form' %>

app/views/consult/register.html.erb
<%= render 'form' %>

app/views/consult/show.html.erb
<%= render 'header' %>
<div class="container home">
  <div class="left">
    <%= image_tag('left_logo.png', class: 'logo') %>
  </div>
  <div class="right consult">
    <div class="consult-show">
      <h1 class="title">
        <%= @consult.question_type %>
      </h1>
      <div class="control-group">
        <div class="control-label">时间:<%= @consult.time %></div>
      </div>
      <div class="control-group">
        <div class="control-label">名称:<%= @consult.title %></div>

      </div>

      <div class="control-group">
        <div class="control-label">地址:<%= @consult.address %></div>

      </div>

      <div class="control-group">
        <div class="control-label">联系人:<%= @consult.contact %></div>

      </div>

      <div class="control-group">
        <div class="control-label">联系电话:<%= @consult.phone %></div>

      </div>

      <div class="control-group">
        <div class="control-label-area">咨询问题:<%= @consult.question %></div>

      </div>

      <div class="control-group">
        <div class="control-label-area">附件<%= link_to '下载', @consult.attachment.url %></div>
      </div>
      <%= render @consult.comments %>
      <%= form_for([@consult, @consult.comments.build], html: {class: 'comment-form'}) do |f| %>
        <div class="control-group">
          <div class="control-label-area">答复意见:</div>
          <%= f.text_area :body, class: 'comment-body' %>
        </div>
        <div class="control-group">
          <div class="control-label-area">附件</div>
          <%= f.file_field :attachment, class: 'btn btn-default' %>
        </div>
          <div class="form-group">
            <%= f.submit '提交' ,class: 'btn btn-lg btn-default btn-block'%>
          </div>
    <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render 'consult/header' %>
<div class="container home">
  <div class="left">
    <%= image_tag('left_logo.png', class: 'logo')%>
  </div>
  <div class="right">
    <div class="title">
      法律服务中心
    </div>
    <div class="items">
      <div class="item"><a class="link" href="consult/law">法律咨询</a></div>
      <div class="item"><a class="link" href="consult/register">立案咨询</a></div>
      <div class="item"><a class="link" href="consult/justice">司法确认</a></div>
      <div class="item"><a class="link" href="consult/flow">案件流程查询</a></div>
      <div class="item"><a class="link" href="consult/feedback">举报投诉</a></div>
      <div class="item"><a class="link" href="consult/complain">信访申诉</a></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lawservicecenter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "登录", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "注册", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "忘记密码?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>